version: "3.7"
services:

  sigepi-db:
    image: mysql:5-debian
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

