/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDAssociarPessoaAEmail.java
 *
 * Created on 06/10/2011, 15:47:54
 */
package br.com.fantonio.sigepi.view.admin;

import br.com.fantonio.sigepi.control.EmailControl;
import java.awt.Color;
import java.awt.Frame;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import br.com.fantonio.sigepi.model.Email;
import br.com.fantonio.sigepi.model.Pessoa;

/**
 *
 * @author Felipe
 */
public class JDAssociarPessoaAEmail extends javax.swing.JDialog {

    private EmailControl controller;
    private Vector<Pessoa> aAssociar, disponiveis;
    private Email email;   
    private List<Pessoa> todasPessoas;
    
    /** Creates new form JDAssociarPessoaAEmail */
    public JDAssociarPessoaAEmail(Frame parent, boolean modal, Email email,
                                  List<Pessoa> todasPessoas) {
        super(parent, modal);
        initComponents(); 
        getContentPane().setBackground(Color.LIGHT_GRAY);
        controller = EmailControl.getInstance();
        this.email = email;       
        this.todasPessoas = todasPessoas;
        iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRodape = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDisponiveis = new javax.swing.JList();
        lblOeste = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAAssociar = new javax.swing.JList();
        lblLeste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Associar pessoas ao email selecionado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setIconImage(null);

        pnlRodape.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlRodape.setPreferredSize(new java.awt.Dimension(580, 50));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRodapeLayout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRodapeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)))
        );

        getContentPane().add(pnlRodape, java.awt.BorderLayout.PAGE_END);

        lstDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDisponiveisMouseClicked(evt);
            }
        });
        lstDisponiveis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstDisponiveisKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstDisponiveis);

        lblOeste.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblOeste.setText("Pessoas disponíveis");

        lstAAssociar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAAssociarMouseClicked(evt);
            }
        });
        lstAAssociar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstAAssociarKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(lstAAssociar);

        lblLeste.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblLeste.setText("Pessoas à associar");

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOeste)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeste)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOeste)
                    .addComponent(lblLeste))
                .addGap(18, 18, 18)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-596)/2, (screenSize.height-406)/2, 596, 406);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDisponiveisMouseClicked
       if (evt.getClickCount() == 2) {
           addPessoaParaListAssociados();
       }
    }//GEN-LAST:event_lstDisponiveisMouseClicked

    private void lstAAssociarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAAssociarMouseClicked
        if (evt.getClickCount() == 2) {
           rmPessoaDeListAssociados();
       }
    }//GEN-LAST:event_lstAAssociarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        email.setPessoas(aAssociar);
        try {
            controller.alterarEmail(email);
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
        } catch (Exception ex) {
            Logger.getLogger(JDAssociarPessoaAEmail.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar salvar o email!\n" +
                                            ex.getMessage());
        }
        finally {
            dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void lstDisponiveisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstDisponiveisKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {                      
            addPessoaParaListAssociados();
        }
    }//GEN-LAST:event_lstDisponiveisKeyPressed

    private void lstAAssociarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstAAssociarKeyPressed
        if (evt.getKeyCode() == evt.VK_DELETE) {                      
             rmPessoaDeListAssociados();
        }
    }//GEN-LAST:event_lstAAssociarKeyPressed
        
    private void iniciar() {
        
        // Cria um vector de pessoas. Ele será usado para demonstrar quais pessoas
        // estão disponíveis para serem associadas
        disponiveis = new Vector<Pessoa>();
        disponiveis.addAll(todasPessoas);
        
        // Cria um vetor de pessoas. Ele será usado para demonstrar as pessoas que
        // serão associadas. Para isso é preciso verificar as pessoas que já estão associadas.
        aAssociar = new Vector<Pessoa>();
        for (int k = 0; k < email.getPessoas().size(); k++) {
            aAssociar.add(email.getPessoas().get(k));
        }
        lstAAssociar.setListData(aAssociar);
        
        // Nesse ponto precisamos remover do vector disponiveis aquelas pessoas
        // que já estão associadas
        Iterator iterador = disponiveis.iterator();
        while (iterador.hasNext()) {
            Pessoa pessoa = (Pessoa) iterador.next();
            for (int k = 0; k < aAssociar.size(); k++) {
                if (aAssociar.get(k).equals(pessoa)) {
                    iterador.remove();
                }
            }
        }
        
        lstDisponiveis.setListData(disponiveis);
        setVisible(true);        
    }    
    
    private void addPessoaParaListAssociados() {
        Pessoa pessoa = (Pessoa)lstDisponiveis.getSelectedValue();
        disponiveis.remove(pessoa);
        aAssociar.add(pessoa);
        lstAAssociar.removeAll();
        lstAAssociar.setListData(aAssociar);
        lstDisponiveis.removeAll();
        lstDisponiveis.setListData(disponiveis);
    }
    
    private void rmPessoaDeListAssociados() {
        Pessoa pessoa = (Pessoa)lstAAssociar.getSelectedValue();
        aAssociar.remove(pessoa);
        disponiveis.add(pessoa);
        lstAAssociar.removeAll();
        lstAAssociar.setListData(aAssociar);
        lstDisponiveis.removeAll();
        lstDisponiveis.setListData(disponiveis);
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLeste;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JList lstAAssociar;
    private javax.swing.JList lstDisponiveis;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlRodape;
    // End of variables declaration//GEN-END:variables
}
